spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"

#    To leverage the individual services info present in the Discovery service so that requests can be routed accordingly.
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # False, if you want to disable the default routes and to enable only custom routes.
          # To consider the service names in the discovery service to lowercase. By default, this is false.
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#To enable the gateway related endpoints in the actuator
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      vishnu:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10   # Specifies the no.of requests to monitor before taking a decision whether to keep the curcuit open or closed.
      permittedNumberOfCallsInHalfOpenState: 2  # no .of requests to be sent when the circuit is o=in half open state
      failureRateThreshold: 50  # If 50%  of the total requests are getting failed, then fall into open state.
      waitDurationInOpenState: 10000 # wait 10 secs in open status before changing into half open state.