services:
  network-deploy-service:
    networks:
      - bank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      #To connect to rabbit service in the container
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      #Defines the profile which needs to be active
      SPRING_PROFILES_ACTIVE: default
      #To connect to config server
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
